### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by buremba** [aholyoke/traildb-java#8]
```
/Users/buremba/Code/dummy/traildb-java/native/src/main/native/TrailDB.c:1:10: fatal error: 'traildb.h' file not found
#include <traildb.h>
         ^
1 error generated.
```

**Comment by aholyoke** [comment]
This looks like a problem with your installation of TrailDB. Are you sure you have TrailDB installed? Alternatively, you can use the docker image by pulling `aholyoke/traildb-java:installed` from Docker Hub.

**Comment by buremba** [comment]
I installed traildb with `brew` but `mvn install -P Mac` still doesn't work. How am I supposed to use the Docker image? I was going to use it as a library in our Java project but Docker containers work as a standalone application.

**Comment by aholyoke** [comment]
Ok, it seems that when you install with brew it puts the headers in a different directory. I have been testing the build with the manual installation of tdb. This means your choices are:

1. Install manually as described in the [official readme](https://github.com/traildb/traildb#build-traildb)
2. checkout this [commit](https://github.com/aholyoke/traildb-java/commit/b7bed1cb26ae2cde46e2f1c9b1a8acd0bda9b6b7) and see if it fixes things

**Comment by buremba** [comment]
Even though `traildb.h` file in `/usr/local/Cellar/traildb/0.6/include` exists, I still see the same error. Any idea?

**Comment by buremba** [comment]
The interesting thing is that I can't even build traildb:

```
Buraks-MacBook-Pro:traildb buremba$ brew install traildb/judy/judy
Warning: traildb/judy/judy 1.0.5 is already installed
Buraks-MacBook-Pro:traildb buremba$ brew link traildb/judy/judy
Warning: Already linked: /usr/local/Cellar/judy/1.0.5
To relink: brew unlink judy && brew link judy
Buraks-MacBook-Pro:traildb buremba$ ./waf configure
Setting top to                           : /Users/buremba/Code/dummy/traildb
Setting out to                           : /Users/buremba/Code/dummy/traildb/build
Checking for 'clang' (C compiler)        : /usr/bin/clang
Checking for program 'pkg-config'        : /usr/local/bin/pkg-config
Checking for 'libarchive'                : yes
Checking for library Judy                : not found; install with 'brew install traildb/judy/judy'
The configuration failed
(complete log in /Users/buremba/Code/dummy/traildb/build/config.log)
```

It complains that `traildb/judy/judy` doesn't exists but as you can see, it's installed. The issue may not be related with this library but do you have any idea/suggestion?

**Comment by buremba** [comment]
Anyway, I found the issue: https://github.com/traildb/traildb/issues/67
Now I'm able to build and run the `Example`. Thanks for the java support for this amazing library, hope you can implement the missing features soon. I would be happy to help if I was familiar with JNI. :/
